branch-defaults:
  develop:
    environment: thisissoon
global:
  application_name: My First Elastic Beanstalk Application
  default_ec2_keyname: soon-eu-vpc
  default_platform: docker
  default_region: eu-west-1
  profile: default
  sc: git